######## 模型微调 ########

### model
model_name_or_path: /media/data/model/huggingface/meta-llama/Llama-2-7b-hf
#adapter_name_or_path: saves/llama2/lora/yelp/sft_pt

### method
# TRAINING_STAGES = {
#    "Supervised Fine-Tuning": "sft",
#    "Reward Modeling": "rm",
#    "PPO": "ppo",
#    "DPO": "dpo",
#    "KTO": "kto",
#    "Pre-Training": "pt",
#}
stage: sft # Supervised Fine-Tuning
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: data/zone
dataset: yelp_ft
template: default # llama3
cutoff_len: 1024
max_samples: 768 # 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama2/lora/yelp/sft_ft_768
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 24
gradient_accumulation_steps: 32
learning_rate: 5.0e-5
num_train_epochs: 50.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 24
eval_strategy: steps
eval_steps: 500
