######## 模型预训练(增量预训练) ########

### model
model_name_or_path: /media/data/model/huggingface/meta-llama/Llama-2-7b-hf
#quantization_bit: 4
#quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: data/zone
dataset: yelp_pt
cutoff_len: 512
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
template: default

### output
output_dir: saves/llama2/lora/yelp/sft_pt
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 50.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
#optim: adamw_torch
#flash_attn: auto

### eval
val_size: 0.1
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 500
