### model
#model_name_or_path: F:/local/data/model/meta-llama/Llama-3-8B
model_name_or_path: saves/models/llama3-8b/Llama-3-8B-Instruct_lora_sft_ml

### method
# TRAINING_STAGES = {
#    "Supervised Fine-Tuning": "sft",
#    "Reward Modeling": "rm",
#    "PPO": "ppo",
#    "DPO": "dpo",
#    "KTO": "kto",
#    "Pre-Training": "pt",
#}
stage: sft # Supervised Fine-Tuning
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: data/zone
dataset: ml-100k_ft
template: llama3 # llama3
cutoff_len: 512
max_samples: 500
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama-3-8b/lora/sft/ml
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 32
learning_rate: 1.0e-4
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500
