### model
#model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
#model_name_or_path: F:/local/data/model/meta-llama/Llama-3-8B # 基础版
model_name_or_path: /media/data/model/huggingface/meta-llama/Llama-3-8B-Instruct # 指令调优版

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: data/zone
dataset: ml-100k_pretrain
cutoff_len: 512
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/sft/ml/pretrain
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
#optim: adamw_torch
template: default
flash_attn: auto

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 500
